### ISSUE TITLE
Error: Reading stdin failed - Unable to join server

### ISSUE THREAD

**Issue by CptPie** [dtandersen/docker_factorio_server#100]
After starting the Server i get the Error Message ```Error InterruptibleStdioStream.cpp:54: Reading stdin failed``` 
When joining the server i get the message: ```UnparsedNetworkMessage.cpp:87: Invalid packet (type ConnectionRequest) received ... : couldn't read from input file.```

It might be possible that i am missing some dependencies (cpp compiler?) since i am running the server on a arch system.

It would be nice if someone could help me :)

**Comment by dtandersen** [comment]
Give the command line used to start the container and the complete log. Also make sure client/server are same version.

**Comment by CptPie** [comment]
I am an idiot i was connecting with 0.15 client :/ thank you for your response and for your work on this docker package
