### ISSUE TITLE
0.16.x Scenario?

### ISSUE THREAD

**Issue by jonfairbanks** [dtandersen/docker_factorio_server#113]
Is it possible to create a scenario branch that supports 0.16.x?

Thanks!

**Comment by dtandersen** [comment]
You can override the entrypoint to run factorio with custom parameters.

**Comment by bplein** [comment]
@jonfairbanks Thanks for asking this. After reading the response from @dtandersen I created an a directory in the volume defined in this image, and put alternate scripts (like to do scenario2map or to launch a specific scenario) in that directory. 

Thank you @dtandersen for making this image open source.

**Comment by dtandersen** [comment]
I'd like to support it, but here's the problem.

In the Dockerfile:

```
CMD [...
  "--rcon-password",
 "$(cat $CONFIG/rconpw)" 
...
```

Literally turns into `/docker-entrypoint.sh $(cat $CONFIG/rconpw)`, instead of `/docker-entrypoint.sh secret'.

**Comment by bplein** [comment]
@dtandersen I've been playing around with this and the right way to address scenarios is to modify your dockerfile to create the symlink just as you do for mods and saves. I'm new to Git, would you like me to put this request in via a pull request? It would be a good learning experience for me but I don't want to waste your time on my newbie-ness.

**Comment by bplein** [comment]
i just saw your response about the custom CMD. I didn't ask for that, hopefully I'm not creating more work for you than necessary. 

For now I have my own /factorio/entrypoints directory for custom entrypoint, so its in the volume and can be referenced by the docker run command. The image needs a scenarios directory, as a symlink pointing to the volume at /factorio/scenarios so we can add scenarios to the game persistently. I've got this working at home but of course I lose the symbolic link if I "rm" the container.

**Comment by dtandersen** [comment]
Sure, go ahead. I've actually never run a scenario so this will be educational.

**Comment by bplein** [comment]
OK, I've got it ready, I'll be sending over a pull request.

**Comment by bplein** [comment]
To test a scenario, you can do the following:

```
cd scenarios
git clone https://github.com/Oarcinae/FactorioScenarioMultiplayerSpawn.git
cd FactorioScenarioMultiplayerSpawn/
git checkout dev_0.16
```
That will download the OARC scenario from GitHub. You don't have to modify the config.lua to test although it would make sense to do so for a real game.

**Comment by bplein** [comment]
Any comments on the pull request?

**Comment by jonfairbanks** [comment]
Sorry for the delay on this, but when passing in the scenario with the flag as recommended I am not seeing my scenario loaded.

`docker run -d --name="FactorioHeadless" --net="host" -e TZ="America/Los_Angeles" -e HOST_OS="unRAID" -e "name"="Testing 123" -e "restart"="always" -e "start-server-load-scenario"="FactorioScenarioMultiplayerSpawn" -v "/mnt/user/Files/Configs/Factorio/":"/factorio":rw --restart=unless-stopped dtandersen/factorio:latest`

In my case, using the command above allows the game to launch and it can be joined externally, however the scenario is not available. 

When digging into the docker logs, I see the following entry which makes it seem like the scenario flag was not passed through:

`0.000 Program arguments: "/opt/factorio/bin/x64/factorio" "--port" "34197" "--start-server-load-latest" "--server-settings" "/factorio/config/server-settings.json" "--server-whitelist" "/factorio/config/server-whitelist.json" "--server-banlist" "/factorio/config/server-banlist.json" "--rcon-port" "27015" "--rcon-password" "xxxxxxxxxxxxx" "--server-id" "/factorio/config/server-id.json"`

I manually created my scenarios/ folder where as @bplein and https://github.com/dtandersen/docker_factorio_server/pull/115/files are declaring this up in the dockerfile, but permissions match with the mods folder and mods are loaded successfully. 

I've also confirmed that `FactorioScenarioMultiplayerSpawn` does not have any critical bugs as I can run mods + this scenario on a Windows host. 

Anything else I can be checking here?

**Comment by bplein** [comment]
The pull request that I am offering does NOT enable the launching via docker run extended command line arguments. What it supports is the alternate entrypoint support I added.

Example:
```
docker run -d \
-p 34197:34197/udp \
-p 27015:27015/tcp \
-v /opt/factorio:/factorio \
--name factorio \
--restart=always  \
--entrypoint "/factorio/entrypoints/scenario.sh" \
dtandersen/factorio \
MyScenarioName
```
the file I added called scenario.sh is launching factorio with scenario options similar to what you are doing. You pass it the scenario name as the final argument to the --entrypoint part of the command line.

**Comment by bplein** [comment]
@dtandersen Will you accept my pull request? It's been outstanding for a while, If you aren't going to use it, I'll fork and do my own thing, I guess, but I'd rather contribute to this and use it. Thanks!

**Comment by jonfairbanks** [comment]
+1 to @bplein's request. I am still unclear on how to enable scenarios in the current fork. @bplein's solution could work, but it being outside of this repo currently makes Docker updates a bit more challenging.

**Comment by dtandersen** [comment]
Ok, finally merged it. It's on the dev tag on docker hub.
