### ISSUE TITLE
Angel's Mod Compatability

### ISSUE THREAD

**Issue by spitefultowel** [dtandersen/docker_factorio_server#114]
I tried running the docker container with mods. It runs no issues with Mods but as soon as I activate Angels petro chem, angels refining, and angels smelting it goes into an infinite crash loop. Same mods run with no issues on 16.16 client.

>   0.000 2018-01-16 19:17:43; Factorio 0.16.16 (build 34924, linux64, headless)
>    0.000 Operating system: Linux
>    0.000 Program arguments: "/opt/factorio/bin/x64/factorio" "--create" "/factorio/saves/_autosave1.zip" "--map-gen-settings" "/factorio/config/map-gen-settings.json" "--map-settings" "/factorio/config/map-settings.json" 
>    0.000 Read data path: /opt/factorio/data
>    0.000 Write data path: /opt/factorio [62339/81908MB]
>    0.000 Binaries path: /opt/factorio/bin
>    0.012 System info: [CPU: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, 4 cores, RAM: 7822MB]
>    0.012 Running in headless mode
>    0.137 Loading mod settings bobenemies 0.16.0 (settings.lua)
>    0.137 Loading mod settings bobinserters 0.16.3 (settings.lua)
>    0.138 Loading mod settings bobores 0.16.1 (settings.lua)
>    0.138 Loading mod settings bobvehicleequipment 0.16.0 (settings.lua)
>    0.138 Loading mod settings bobplates 0.16.0 (settings.lua)
>    0.139 Loading mod settings rso-mod 3.5.4 (settings.lua)
>    0.139 Loading mod settings bobassembly 0.16.0 (settings.lua)
>    0.140 Loading mod settings boblogistics 0.16.3 (settings.lua)
>    0.140 Loading mod settings bobmining 0.16.0 (settings.lua)
>    0.141 Loading mod settings angelsrefining 0.9.7 (settings.lua)
>    0.141 Loading mod settings bobmodules 0.16.0 (settings.lua)
>    0.142 Loading mod settings bobwarfare 0.16.0 (settings.lua)
>    0.142 Loading mod settings angelsaddons-oresilos 0.4.0 (settings.lua)
>    0.143 Loading mod settings angelsaddons-warehouses 0.3.0 (settings.lua)
>    0.143 Loading mod settings angelspetrochem 0.7.4 (settings.lua)
>    0.150 Loading mod core 0.0.0 (data.lua)
>    0.176 Loading mod base 0.16.16 (data.lua)
>    0.422 Loading mod FARL 2.0.2 (data.lua)
>    0.505 Loading mod angelsaddons-petrotrain 0.3.2 (data.lua)
>    0.591 Loading mod bobenemies 0.16.0 (data.lua)
>    0.687 Loading mod bobinserters 0.16.3 (data.lua)
>    0.753 Loading mod boblibrary 0.16.1 (data.lua)
>    0.812 Loading mod bobores 0.16.1 (data.lua)
>    0.881 Loading mod bobtech 0.16.0 (data.lua)
>    0.940 Loading mod bobvehicleequipment 0.16.0 (data.lua)
>    1.015 Loading mod bobplates 0.16.0 (data.lua)
>    1.082 Loading mod rso-mod 3.5.4 (data.lua)
>    1.146 Loading mod bobassembly 0.16.0 (data.lua)
>    1.214 Loading mod bobelectronics 0.16.0 (data.lua)
>    1.285 Loading mod bobgreenhouse 0.16.0 (data.lua)
>    1.372 Loading mod boblogistics 0.16.3 (data.lua)
>    1.472 Loading mod bobmining 0.16.0 (data.lua)
>    1.565 Loading mod bobpower 0.16.1 (data.lua)
>    1.654 Loading mod bobrevamp 0.16.0 (data.lua)
>    1.760 Loading mod angelsrefining 0.9.7 (data.lua)
>    1.897 Loading mod bobmodules 0.16.0 (data.lua)
>    1.998 Loading mod bobwarfare 0.16.0 (data.lua)
>    2.136 Loading mod angelsaddons-oresilos 0.4.0 (data.lua)
>    2.260 Loading mod angelsaddons-warehouses 0.3.0 (data.lua)
>    2.357 Loading mod angelspetrochem 0.7.4 (data.lua)
>    2.543 Loading mod angelsaddons-pressuretanks 0.3.0 (data.lua)
>    2.675 Loading mod angelssmelting 0.4.2 (data.lua)
>    2.891 Loading mod base 0.16.16 (data-updates.lua)
>    3.081 Loading mod FARL 2.0.2 (data-updates.lua)
>    3.253 Loading mod angelsaddons-petrotrain 0.3.2 (data-updates.lua)
>    3.432 Loading mod bobenemies 0.16.0 (data-updates.lua)
>    3.637 Loading mod bobinserters 0.16.3 (data-updates.lua)
>    3.829 Loading mod Squeak Through 1.1.8 (data-updates.lua)
>    4.039 Loading mod bobores 0.16.1 (data-updates.lua)
>    4.287 Loading mod bobtech 0.16.0 (data-updates.lua)
>    4.534 Loading mod bobvehicleequipment 0.16.0 (data-updates.lua)
>    4.786 Loading mod bobplates 0.16.0 (data-updates.lua)
>    4.796 Script @__boblibrary__/module-functions.lua:12: Recipe polishing-wheel-synthetic does not exist.
>    5.045 Loading mod rso-mod 3.5.4 (data-updates.lua)
>    5.197 Loading mod bobassembly 0.16.0 (data-updates.lua)
>    5.390 Loading mod bobelectronics 0.16.0 (data-updates.lua)
>    5.569 Loading mod bobgreenhouse 0.16.0 (data-updates.lua)
>    5.707 Loading mod boblogistics 0.16.3 (data-updates.lua)
>    5.872 Loading mod bobmining 0.16.0 (data-updates.lua)
>    6.038 Loading mod bobpower 0.16.1 (data-updates.lua)
>    6.199 Loading mod bobrevamp 0.16.0 (data-updates.lua)
>    6.379 Loading mod angelsrefining 0.9.7 (data-updates.lua)
>    6.575 Loading mod bobmodules 0.16.0 (data-updates.lua)
>    6.792 Loading mod bobwarfare 0.16.0 (data-updates.lua)
>    6.795 Script @__boblibrary__/recipe-functions.lua:76: Recipe gun-cotton-synthetic does not exist.
>    6.800 Script @__boblibrary__/module-functions.lua:12: Recipe gun-cotton-synthetic does not exist.
>    6.958 Loading mod angelsaddons-oresilos 0.4.0 (data-updates.lua)
>    7.095 Loading mod angelsaddons-warehouses 0.3.0 (data-updates.lua)
>    7.290 Loading mod angelspetrochem 0.7.4 (data-updates.lua)
>    7.488 Loading mod angelssmelting 0.4.2 (data-updates.lua)
>    7.727 Loading mod FARL 2.0.2 (data-final-fixes.lua)
>    7.945 Loading mod bobelectronics 0.16.0 (data-final-fixes.lua)
>    8.317 Loading mod angelsrefining 0.9.7 (data-final-fixes.lua)
>    8.587 Loading mod angelspetrochem 0.7.4 (data-final-fixes.lua)
>    8.873 Loading mod angelssmelting 0.4.2 (data-final-fixes.lua)
>    9.153 Checksum for core: 2242385247
>    9.153 Checksum of base: 354110265
>    9.153 Checksum of FARL: 1212406221
>    9.153 Checksum of angelsaddons-petrotrain: 2230445547
>    9.153 Checksum of bobenemies: 663681064
>    9.153 Checksum of bobinserters: 2634251498
>    9.153 Checksum of boblibrary: 59313886
>    9.153 Checksum of Squeak Through: 3430405470
>    9.153 Checksum of bobores: 3418552415
>    9.153 Checksum of bobtech: 2754529862
>    9.153 Checksum of bobvehicleequipment: 1214461171
>    9.153 Checksum of bobplates: 588373870
>    9.153 Checksum of rso-mod: 2237909465
>    9.153 Checksum of bobassembly: 262568743
>    9.153 Checksum of bobelectronics: 3969922877
>    9.153 Checksum of bobgreenhouse: 540722007
>    9.153 Checksum of boblogistics: 2304631358
>    9.153 Checksum of bobmining: 1108206312
>    9.153 Checksum of bobpower: 4191124
>    9.153 Checksum of bobrevamp: 2386249982
>    9.153 Checksum of angelsrefining: 2382621356
>    9.153 Checksum of bobmodules: 4185527414
>    9.153 Checksum of bobwarfare: 416552353
>    9.153 Checksum of angelsaddons-oresilos: 101581399
>    9.153 Checksum of angelsaddons-warehouses: 438730778
>    9.153 Checksum of angelspetrochem: 1670625785
>    9.153 Checksum of angelsaddons-pressuretanks: 1522968118
>    9.153 Checksum of angelssmelting: 440158107
>    9.680 Info PlayerData.cpp:65: Local player-data.json available, timestamp 1516130262
>    9.680 Info PlayerData.cpp:72: Cloud player-data.json unavailable
>    9.690 Custom inputs active: 0
>    9.690 Factorio initialised
>    9.690 Info GlobalContext.cpp:671: Waiting for child processes to exit: 
>    9.744 Goodbye
>    0.000  Error Util.cpp:49: "copper-ore" is not a valid autoplace control name.
> uid=845(factorio) gid=845(factorio) groups=845(factorio)
>    0.000 2018-01-16 19:17:54; Factorio 0.16.16 (build 34924, linux64, headless)

**Comment by dtandersen** [comment]
I'm not sure what the problem could be. It just reads the mods from the mods folder.

**Comment by spitefultowel** [comment]
It works just fine with angelsrefining_0.9.7 but crashes with the same error as soon as angelspetrochem_0.7.4 is added.

**Comment by spitefultowel** [comment]
Neither am I :( Hence the ticketing here... It really makes no sense why it works with the 16.16 client, but not with your docker container... I guess I could try a standard headless server to test and see if the same issue is there... If it is then it would have to be an issue with the mod itself.

**Comment by bplein** [comment]
@spitefultowel If you post a list of all the mods you are using then I can try and reproduce. 

I don't play with mods, so I start with a clean mods directory. I downloaded the following:
angelspetrochem_0.7.4.zip
angelsrefining_0.9.7.zip
angelssmelting_0.4.2.zip
boblibrary_0.16.1.zip

That must not be sufficient because you have a lot more things loading there. Give me a specific list and I'm happy to try it out. I don't want to try and reverse engineer it from your output however.

**Comment by spitefultowel** [comment]
bplein, I actually reduced all loaded mods to just the angels stuff which were causing issues. List from my PC (not the docker container) is below.

> -rw-r--r-- 1 spite 197609   390557 Jan 16 12:25  FARL_2.0.2.zip
> -rw-r--r-- 1 spite 197609    17381 Jan 16 12:26 'Squeak Through_1.1.8.zip'
> -rw-r--r-- 1 spite 197609   508512 Jan 16 13:02  angelsaddons-oresilos_0.4.0.zip
> -rw-r--r-- 1 spite 197609 13130967 Jan 16 13:03  angelsaddons-petrotrain_0.3.2.zip
> -rw-r--r-- 1 spite 197609    93639 Jan 16 13:03  angelsaddons-pressuretanks_0.3.0.zip
> -rw-r--r-- 1 spite 197609   409553 Jan 16 13:02  angelsaddons-warehouses_0.3.0.zip
> -rw-r--r-- 1 spite 197609 12701490 Jan 16 13:02  angelspetrochem_0.7.4.zip
> -rw-r--r-- 1 spite 197609 36238029 Jan 16 13:02  angelsrefining_0.9.7.zip
> -rw-r--r-- 1 spite 197609 18275540 Jan 16 13:02  angelssmelting_0.4.2.zip
> -rw-r--r-- 1 spite 197609  1598597 Jan 16 12:30  bobassembly_0.16.0.zip
> -rw-r--r-- 1 spite 197609   190555 Jan 16 12:30  bobelectronics_0.16.0.zip
> -rw-r--r-- 1 spite 197609   155741 Jan 16 12:31  bobenemies_0.16.0.zip
> -rw-r--r-- 1 spite 197609   113131 Jan 16 12:31  bobgreenhouse_0.16.0.zip
> -rw-r--r-- 1 spite 197609   127755 Jan 16 12:30  bobinserters_0.16.3.zip
> -rw-r--r-- 1 spite 197609  6833519 Jan 16 12:31  boblibrary_0.16.1.zip
> -rw-r--r-- 1 spite 197609  3252812 Jan 16 12:31  boblogistics_0.16.3.zip
> -rw-r--r-- 1 spite 197609   377660 Jan 16 12:32  bobmining_0.16.0.zip
> -rw-r--r-- 1 spite 197609   103160 Jan 16 12:30  bobmodules_0.16.0.zip
> -rw-r--r-- 1 spite 197609    97949 Jan 16 12:30  bobores_0.16.1.zip
> -rw-r--r-- 1 spite 197609  1059135 Jan 16 12:31  bobplates_0.16.0.zip
> -rw-r--r-- 1 spite 197609   116558 Jan 16 12:30  bobpower_0.16.1.zip
> -rw-r--r-- 1 spite 197609    88923 Jan 16 12:31  bobrevamp_0.16.0.zip
> -rw-r--r-- 1 spite 197609   837159 Jan 16 12:32  bobtech_0.16.0.zip
> -rw-r--r-- 1 spite 197609  1991641 Jan 16 12:31  bobvehicleequipment_0.16.0.zip
> -rw-r--r-- 1 spite 197609  1000662 Jan 16 12:32  bobwarfare_0.16.0.zip
> -rw-r--r-- 1 spite 197609    50291 Jan 16 13:08  rso-mod_3.5.4.zip

**Comment by bplein** [comment]
So are you saying that only angels is required to reproduce? I can ignore and not download rso, bobs, "Squeak" and FARL? 

What is in the mods directory on the docker container? That's where you are having the problem. Showing the list from another location doesn't do any good if they aren't the same.

**Comment by spitefultowel** [comment]
@bplein it's the same list of mods, but with just angel's petro (which requires angel's refining) I can reproduce. Angel's refining by itself doesn't cause issues (which is why I believe it may just be a mod issue.

**Comment by RoboPhred** [comment]
@spitefultowel I just ran into this; and it turns out this is a simple configuration error.

The issue happens because of the default map-gen-settings.json that the container tries to use:
```
{
    "_comment": "Sizes can be specified as none, very-low, low, normal, high, very-high",
  
    "terrain_segmentation": "normal",
    "water": "normal",
    "width": 0,
    "height": 0,
    "starting_area": "normal",
    "peaceful_mode": false,
    "autoplace_controls":
    {
      "trees":  {"frequency":  "normal", "size": "normal", "richness": "normal"},
      "coal": {"frequency": "normal", "size": "normal", "richness": "normal"},
      "copper-ore": {"frequency": "normal", "size": "normal", "richness": "normal"},
      "crude-oil": {"frequency": "normal", "size": "normal", "richness": "normal"},
      "enemy-base": {"frequency": "normal", "size": "normal", "richness": "normal"},
      "iron-ore": {"frequency": "normal", "size": "normal", "richness": "normal"},
      "stone": {"frequency": "normal", "size": "normal", "richness": "normal"},
      "uranium-ore": {"frequency": "normal", "size": "normal", "richness": "normal"}
    },
  
    "_comment_seed": "Use null for a random seed, number for a specific seed.",
    "seed": null
  }
```

Note the autoplace_controls property, and how it has a "copper-ore" setting.  This is the setting that the game is choking on.  Angel refining disables all stock ores aside from copper, and the map generator complains when you try to set up ore spawning for an ore it does not understand.

To fix this and get the mod running on the server, you need to set up a map-gen-settings.json file with the correct autoplace settings for the ores that angels expects.

For example, I am using this map-gen-settings file
```
{
    "_comment": "Sizes can be specified as none, very-low, low, normal, high, very-high",
  
    "terrain_segmentation": "normal",
    "water": "normal",
    "width": 0,
    "height": 0,
    "starting_area": "normal",
    "peaceful_mode": false,
    "autoplace_controls":
    {
      "trees":  {"frequency":  "normal", "size": "normal", "richness": "normal"},
      "coal": {"frequency": "normal", "size": "normal", "richness": "very-good"},
      "angels-ore1": {"frequency": "normal", "size": "high", "richness": "very-good"},
      "angels-ore2": {"frequency": "normal", "size": "high", "richness": "very-good"},
      "angels-ore3": {"frequency": "normal", "size": "high", "richness": "very-good"},
      "angels-ore4": {"frequency": "normal", "size": "high", "richness": "very-good"},
      "angels-fissure": {"frequency": "normal", "size": "normal", "richness": "very-good"},
      "crude-oil": {"frequency": "normal", "size": "normal", "richness": "very-good"},
      "enemy-base": {"frequency": "normal", "size": "normal", "richness": "normal"}
    },
  
    "_comment_seed": "Use null for a random seed, number for a specific seed.",
    "seed": null
  }
```

Adjust the settings to your liking, and place this in whatever directory you volume-mount to the container's /factorio directory.

**Comment by spitefultowel** [comment]
@RoboPhred awesome info! Using your config fixed it all. :-)

**Comment by nicekiwi** [comment]
I had the same issue today. 

For me it was enough to remove the values that threw the error so my object looked like this:

```
  "autoplace_controls":
  {
    "trees":  {"frequency": 1, "size": 1, "richness": 1},
    "enemy-base": {"frequency": 1, "size": 1, "richness": 1}
  },
```
