### ISSUE TITLE
Reversed arguments to adduser

### ISSUE THREAD

**Issue by yukihyou** [dtandersen/docker_factorio_server#116]
While doing some other testing with this image, I noticed that the `$USER` and `$GROUP` arguments are reversed in the adduser line - this normally wouldn't cause any problems unless they don't match.

https://github.com/dtandersen/docker_factorio_server/blob/189395d5c88f2f7cf8980230fda85aed3f3d227e/0.16/Dockerfile#L28
should be

`adduser -u $PUID -G $GROUP -s /bin/sh -SDH $USER && \`

**Comment by psykzz** [comment]
Hows this https://github.com/dtandersen/docker_factorio_server/pull/129?
