### ISSUE TITLE
Snippet to store factorio data in the volume

### ISSUE THREAD

**Issue by devsli** [dtandersen/docker_factorio_server#117]
I'm a big fan of volumes, so here a short snippet to store factorio data in its own volume:

    sudo docker volume create factorio

    sudo docker run --rm -v factorio:/factorio alpine chown 845:845 /factorio

    sudo docker run -d \
      -p 34197:34197/udp \
      -p 27015:27015/tcp \
      -v factorio:/factorio \
      --name factorio \
      --restart=always  \
      dtandersen/factorio

**Comment by devsli** [comment]
The volume mentioned in README.md is a folder you need to specify in your filesystem. I think default Docker volumes are more consistent.

**Comment by bplein** [comment]
They are both volumes. Thanks to Docker, a single command line does both a volume and bind volume and you can only tell which is which by inspection (i.e. if it's a host path it's a bind volume). The benefit here of a bind volume is that you can access it easily from your host and populate it with game saves, mods, etc. Even if your host is, say in my example, macOS. 

Maybe the README.md could just show two examples, one using a pure volume (leave it to the user to determine the best way to get at the files) or the bind volume as noted.

**Comment by devsli** [comment]
> Maybe the README.md could just show two examples

Sounds overcomplicated, I think current solution is fine.
