### ISSUE TITLE
tag 0.13.33 in latest build

### ISSUE THREAD

**Issue by bplein** [dtandersen/docker_factorio_server#147]
There's a tag for 0.13.33 on the latest build that should probably be 0.16.33.

I use the following code to find the latest version of your repository:

git describe --tags `git rev-list --tags`

Since this release, it's responding with 0.13.33

Is there a better way to find out (from a bash script) what the newest release from you is? Maybe I'm doing it incorrectly :)

**Comment by dtandersen** [comment]
I'd probably pull all the tags and sort them. Deleted that offending tag.

**Comment by bplein** [comment]
thanks.

**Comment by bplein** [comment]
Since there can be a delay in docker image build vs. github update, I really should be checking there. I think I've got a working sort :)

Thanks again for all you do!
