### ISSUE TITLE
Logs not preserved on "docker rm" or similar

### ISSUE THREAD

**Issue by bplein** [dtandersen/docker_factorio_server#151]
Since logs kept in /opt/factorio (factorio-current.log and factorio-previous.log), they are lost when the container is removed. 

For admins, having these logs go to a persistent volume allows you to go through and check them out even if a container has been restarted with a new version.

There is a console log CLI option, one for path/name and another controlling log rotation. If these could be pointed to another location (like another volume) that would solve it. 

What would be the best way to handle this? Is using an alternate entrypoint (and not changing the code in this current project) probably the best way? Trying to think how using this might break going forward (if at all)

Thanks in advance.

**Comment by dtandersen** [comment]
You could mount /var/log/factorio.log:/opt/factorio/factorio-current.log and then use logrotate.

**Comment by bplein** [comment]
I will give that a try, thanks. Closing this for now.
