### ISSUE TITLE
0.16.45 didn't push to dockerhub

### ISSUE THREAD

**Issue by nevir** [dtandersen/docker_factorio_server#164]
Looks like 0.16.45 [isn't available on docker hub yet](https://hub.docker.com/r/dtandersen/factorio/tags/) (did you forget to push the image, or is that automated elsewhere?)

**Comment by nevir** [comment]
And when trying to build manually: https://gist.github.com/nevir/6130c89a3bb376fe8ad9b076e7ec4f43

```
/tmp/factorio_headless_x64_0.16.45.tar.xz: FAILED
sha1sum: WARNING: 1 of 1 computed checksums did NOT match
```

**Comment by nevir** [comment]
https://github.com/dtandersen/docker_factorio_server/pull/165 seems to be the correct sha

**Comment by Fank** [comment]
That's weired, i didn't changed anything of the checksum stuff.
```
time="2018-05-22T20:07:43Z" level=info msg="Start 0.16.45"
time="2018-05-22T20:07:46Z" level=info msg="Cloned repo"
time="2018-05-22T20:07:47Z" level=info msg="Got checksum 994bc667720c21257500e29038c1a5f61e25da1e"
time="2018-05-22T20:07:47Z" level=info msg="Edited Dockerfile"
time="2018-05-22T20:07:47Z" level=info msg="Edited README"
time="2018-05-22T20:07:47Z" level=info msg=Committed
time="2018-05-22T20:07:51Z" level=info msg=Pushed
time="2018-05-22T20:07:54Z" level=info msg=Tagged
```
Maybe a wrong file was uploaded at the same time as they released it...

**Comment by Fank** [comment]
I manualy fixed and pushed it, version should be available soon.
