### ISSUE TITLE
latest tag didn't get updated

### ISSUE THREAD

**Issue by Skaronator** [dtandersen/docker_factorio_server#166]
The `latest` tag is still on `0.16.43`. The correct version is `0.16.45`.

https://hub.docker.com/r/dtandersen/factorio/tags/

**Comment by Fank** [comment]
@dtandersen it looks like you need to change how latest tag is build, because its outdated again.

**Comment by Fank** [comment]
@dtandersen please send me following information via email:
![image](https://user-images.githubusercontent.com/1900106/40921060-afbd6f86-680e-11e8-9de4-7535e3eaba7d.png)
So i could trigger latest build manually.
And add a build setting with "latest" which build "latest"

**Comment by dtandersen** [comment]
What is your dockerhub username?

**Comment by Fank** [comment]
fank

**Comment by dtandersen** [comment]
i added you to the repo

**Comment by Skaronator** [comment]
0.16.48 didn't build successfully on Docker hub

https://hub.docker.com/r/dtandersen/factorio/builds/bpkk47xq7k4tvfds9yhjacb/

**Comment by Fank** [comment]
hm looks like the build system is faster than they publish the file to download

**Comment by dtandersen** [comment]
Fank you hacked time too far.

**Comment by VonOx** [comment]
So latest tag is ok now ?

**Comment by Fank** [comment]
I received build info yesterday, i may have time to take a look in it, end next week.

**Comment by Skaronator** [comment]
You can use `0.16-dev` in the meantime
