### ISSUE TITLE
Is latest tied to a specific version line?

### ISSUE THREAD

**Issue by bkuhl** [dtandersen/docker_factorio_server#17]
The readme indicates there's a readme, but it seems it could be a patch to 0.14 or 0.15.  While this historically may not be true, it'd be nice if there was a 0.15-latest so people can setup automated deployments without concerns over whether it'd break their current build.

It'd be particularly useful for when features are back ported such as https://github.com/dtandersen/docker_factorio_server/issues/3

**Comment by AgentME** [comment]
There are 0.14 and 0.15 tags that have the latest 0.14.x and 0.15.x versions.

**Comment by bkuhl** [comment]
Ah, good call!
