### ISSUE TITLE
Docker Pulling exact version still seems to pull wrong version

### ISSUE THREAD

**Issue by tflinz** [dtandersen/docker_factorio_server#171]
I pull down the exact version:
> 0.16.47: Pulling from dtandersen/factorio
> Digest: sha256:50d24d718e46e51a9d0ba9edaa5eb09ec11f2e0488adca22e7bfb6a351e6e916
> Status: Image is up to date for dtandersen/factorio:0.16.47

But when this container fires up, and I try to connect it still says it is running 0.16.46.

At first I thought it was that latest wasn't pointing to 0.16.47... 
(similar to this: https://github.com/dtandersen/docker_factorio_server/issues/166)
But, even pulling the specific image seems to still be starting a 0.16.46 server.
:/

Not sure what is up.
(but I have had this similar mismatch issue a few times for other versions as well in the past month or so)

**Comment by Fank** [comment]
Ill validate this.

**Comment by Fank** [comment]
```
$ docker run --rm -it dtandersen/factorio:0.16.47
Unable to find image 'dtandersen/factorio:0.16.47' locally
0.16.47: Pulling from dtandersen/factorio
ff3a5c916c92: Already exists 
c4f576d46465: Pull complete 
edebedd9043d: Pull complete 
fbc80f8f72f4: Pull complete 
Digest: sha256:50d24d718e46e51a9d0ba9edaa5eb09ec11f2e0488adca22e7bfb6a351e6e916
Status: Downloaded newer image for dtandersen/factorio:0.16.47
```
...
```
+ /opt/factorio/bin/x64/factorio --create /factorio/saves/_autosave1.zip --map-gen-settings /factorio/config/map-gen-settings.json --map-settings /factorio/config/map-settings.json
   0.000 2018-06-04 13:56:45; Factorio 0.16.47 (build 36587, linux64, headless)
   0.000 Operating system: Linux
```

could you post your log?

**Comment by tflinz** [comment]
just poking around now, I'll let you know what I turn up. :)

**Comment by tflinz** [comment]
Alright, I got it figured out.

It was related to the other issue about "latest" not being latest.
I have two scripts one for update.sh and one start.sh, the last few times I ran them I had forgotten to update the version they were referencing in start.sh (so it was still trying to load up :latest)
*Fixed it so start just takes the tag in as an argument now

And so, yes .47 behaves as expected. :)
