### ISSUE TITLE
Add auto chown to runscript

### ISSUE THREAD

**Issue by MeFisto94** [dtandersen/docker_factorio_server#172]
Pretty much what the title says: To prevent the user from manually chowning the configs, we could automatically chown them in the run script before we drop the privilegs.

In addition to that one could specify a UID environment variable, so the host could make the container run as their user account so that the config directory is also easily readable from outside. 

What do you guys think?

**Comment by dtandersen** [comment]
Added preliminary support for this in 0.17.
