### ISSUE TITLE
Error on startup UDPSocket.cpp:366

### ISSUE THREAD

**Issue by AvoMMH** [dtandersen/docker_factorio_server#176]
On startup I get the following Error:
`
+ set -e,
+ id,
+ mkdir -p /factorio/saves,
uid=845(factorio) gid=845(factorio) groups=845(factorio),
+ mkdir -p /factorio/config,
+ mkdir -p /factorio/mods,
+ mkdir -p /factorio/scenarios,
+ mkdir -p /factorio/script-output,
+ [ ! -f /factorio/config/rconpw ],
+ [ ! -f /factorio/config/server-settings.json ],
+ [ ! -f /factorio/config/map-gen-settings.json ],
+ [ ! -f /factorio/config/map-settings.json ],
+ find -L /factorio/saves -iname *.tmp.zip -mindepth 1 -print,
+ grep -q .,
+ find -L /factorio/saves -iname *.zip -mindepth 1 -print,
+ grep -q .,
+ cat /factorio/config/rconpw,
+ exec /opt/factorio/bin/x64/factorio --port 34197 --start-server-load-latest --server-settings /factorio/config/server-settings.json --server-whitelist /factorio/config/server-whitelist.json --server-banlist /factorio/config/server-banlist.json --rcon-port 27015 --rcon-password Axo2se3eishalok --server-id /factorio/config/server-id.json,
   0.000 2018-09-11 08:02:31; Factorio 0.16.51 (build 36654, linux64, headless),
   0.000 Operating system: Linux,
   0.000 Program arguments: "/opt/factorio/bin/x64/factorio" "--port" "34197" "--start-server-load-latest" "--server-settings" "/factorio/config/server-settings.json" "--server-whitelist" "/factorio/config/server-whitelist.json" "--server-banlist" "/factorio/config/server-banlist.json" "--rcon-port" "27015" "--rcon-password" <private> "--server-id" "/factorio/config/server-id.json" ,
   0.000 Read data path: /opt/factorio/data,
   0.000 Write data path: /opt/factorio [836580/922950MB],
   0.000 Binaries path: /opt/factorio/bin,
   0.011 System info: [CPU:         Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz, 4 cores, RAM: 7936 MB],
   0.011 Environment: DISPLAY=<unset>, WAYLAND_DISPLAY=<unset>,
   0.011 Running in headless mode,
   0.015 Loading mod core 0.0.0 (data.lua),
   0.030 Loading mod base 0.16.51 (data.lua),
   0.162 Loading mod base 0.16.51 (data-updates.lua),
   0.202 Checksum for core: 840319042,
   0.202 Checksum of base: 3323233190,
   0.298 Info PlayerData.cpp:65: Local player-data.json available, timestamp 1536652948,
   0.298 Info PlayerData.cpp:72: Cloud player-data.json unavailable,
   0.299 Custom inputs active: 0,
   0.299 Factorio initialised,
   0.300 Info ServerSynchronizer.cpp:29: nextHeartbeatSequenceNumber(0) initialized Synchronizer nextTickClosureTick(0).,
   0.300 Info ServerMultiplayerManager.cpp:699: mapTick(4294967295) changing state from(Ready) to(PreparedToHostGame),
   0.300 Info ServerMultiplayerManager.cpp:699: mapTick(4294967295) changing state from(PreparedToHostGame) to(CreatingGame),
   0.300 Loading map /factorio/saves/_autosave1.zip: 657602 bytes.,
   0.311 Loading Level.dat: 941398 bytes.,
   0.316 Info Scenario.cpp:136: Map version 0.16.51-0,
   0.349 Loading script.dat: 176 bytes.,
   0.352 Checksum for script /opt/factorio/temp/currently-playing/control.lua: 950616531,
   0.352 Info UDPSocket.cpp:27: Opening socket at (IP ADDR:({0.0.0.0:34197})),
   0.352 Hosting game at IP ADDR:({0.0.0.0:34197}),
   0.352 Info HttpSharedState.cpp:54: Downloading https://auth.factorio.com/generate-server-padlock-2,
   0.804 Info HttpSharedState.cpp:145: Status code: 200,
   0.804 Info AuthServerConnector.cpp:109: Obtained serverPadlock for serverHash (kJmwMa3Z4sInzf3p9un8IaAlGlE5Vek0) from the auth server.,
   0.804 Info ServerMultiplayerManager.cpp:699: mapTick(0) changing state from(CreatingGame) to(InGame),
   0.804 Info UDPSocket.cpp:39: Opening socket for broadcast,
   0.804 Warning UDPSocket.cpp:366: Sendto failed: Operation not permitted; data length = 3, address = IP ADDR:({10.255.255.255:34196}),
   0.824 Error InterruptibleStdioStream.cpp:54: Reading stdin failed,
   0.825 Info RemoteCommandProcessor.cpp:128: Starting RCON interface at port 27015,
   2.804 Warning UDPSocket.cpp:366: Sendto failed: Operation not permitted; data length = 3, address = IP ADDR:({10.255.255.255:34196}),
`

What could be the reason? How do I get rid of this?
Factoio was running on this maching a while ago wihout problems

**Comment by Thrimbda** [comment]
it looks like there's an internal error occurred in factorio server itself
```bash
0.824 Error InterruptibleStdioStream.cpp:54: Reading stdin failed,
```
but as the warning shows above, it might be a permission issue in your environment, something about network?
```bash
0.804 Warning UDPSocket.cpp:366: Sendto failed: Operation not permitted; data length = 3, address = IP ADDR:({10.255.255.255:34196}),
```

**Comment by AvoMMH** [comment]
It is working now, it just took a few restarts

**Comment by sousandrei** [comment]
I'm having this issue right now. Running on docker swarm.
The IP on the error is an internal swarm IP but the server IP is it's correct external IP
Help :c

**Comment by AvoMMH** [comment]
Have you tried to remove the swarm and reboot? That solved the issue on my system.

**Comment by mylogon341** [comment]
sorry to revive this old thread, but will this not work on a swam? I'm getting this exact same error where it's trying to connect to `({10.0.0.255:34196}),`, which doesn't make sense to me.
i cant see why it wouldn't work... but I guess thats why I'm struggling.

**Comment by mylogon341** [comment]
Ok. after a bit of mucking about this afternoon, I was able to fix it by adding this to the yml 
```yaml
    ports:
      - target: 34197
        published: 34197
        protocol: udp
        mode: host
```
