### ISSUE TITLE
exec format error in factorio logs

### ISSUE THREAD

**Issue by chazragg** [dtandersen/docker_factorio_server#177]
when I set up and run the container using the docker-compose suggest on the docker hub page the container does not show in docker ps as running and when I check the logs I get 

![image](https://user-images.githubusercontent.com/4650060/53042689-c8267d00-347e-11e9-975a-e65b4638a568.png)

**Comment by SuperSandro2000** [comment]
This has nothing to do with the docker-compose. You are trying to run a amd64 image on an arm7/arm8 Pi. Factorio does only support amd64.
This can be closed.
