### ISSUE TITLE
0.17 Gosu

### ISSUE THREAD

**Issue by HannesHil** [dtandersen/docker_factorio_server#181]
Dont know if its to early to ask. 

But I just tried to use the new Image for the Dev Version 0.17 and got this error while starting:

`/docker-entrypoint.sh: exec: line 45: gosu: not found`

**Comment by bplein** [comment]
Confirmed, same here. Looks like gosu isn't in the image.

**Comment by dtandersen** [comment]
Looks like Alpine has su-exec.

https://github.com/tianon/gosu/blob/master/INSTALL.md
