### ISSUE TITLE
0.17 Support

### ISSUE THREAD

**Issue by dtandersen** [dtandersen/docker_factorio_server#184]
~~Use the tag `0.17-debug` for the time being until the kinks are worked out.~~

**Comment by seigieu** [comment]
@dtandersen Not sure if it matters for 0.17, not sure what "kinks" are:
```
exec gosu factorio /opt/factorio/bin/x64/factorio --port 34198 --start-server-load-latest --server-settings /factorio/config/server-settings.json --server-whitelist /factorio/config/server-whitelist.json --server-banlist /factorio/config/server-banlist.json --rcon-port 27015 --rcon-password ***** --server-id /factorio/config/server-id.json
/docker-entrypoint.sh: exec: line 45: gosu: not found
```

**Comment by dtandersen** [comment]
I think that's fixed in the image  `dtandersen/factorio:0.17-debug`.

**Comment by saibotk** [comment]
Thank you for your effort ;)

**Comment by dtandersen** [comment]
0.17.1 ready for testing!

**Comment by Fank** [comment]
i need to validate that the version bot still works with 0.17

**Comment by nexusmaniac** [comment]
Started from scratch with this container and getting errors on launch. Not sure what I can do to further diagnose 😄 I'm running the `latest` (0.17.1)

```
0.788 Factorio initialised
0.789 Info ServerSynchronizer.cpp:29: nextHeartbeatSequenceNumber(0) initialized Synchronizer nextTickClosureTick(0).
0.789 Info ServerMultiplayerManager.cpp:714: updateTick(4294967295) changing state from(Ready) to(PreparedToHostGame)
0.789 Info ServerMultiplayerManager.cpp:714: updateTick(4294967295) changing state from(PreparedToHostGame) to(CreatingGame)
0.790 Loading map /factorio/saves/_autosave1.zip: 949263 bytes.
0.792 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "filesystem error: create_directories "/opt/factorio/temp/currently-playing" failed: Permission denied [/opt/factorio/temp/currently-playing]"

0.792 Info ServerMultiplayerManager.cpp:714: updateTick(4294967295) changing state from(CreatingGame) to(InitializationFailed)
0.792 Info GlobalContext.cpp:677: Waiting for child processes to exit:
0.792 Info ServerMultiplayerManager.cpp:138: Quitting multiplayer connection.
0.792 Info ServerMultiplayerManager.cpp:714: updateTick(4294967295) changing state from(InitializationFailed) to(Closed)
0.793 Warning WriteFileGuard.cpp:96: Couldn't chown /opt/factorio/player-data.tmp.json: Operation not permitted

0.808 Info UDPSocket.cpp:210: Closing socket
0.808 Goodbye
```

**Comment by seigieu** [comment]
@dtandersen Indeed "debug" one works. What's the difference?

**Comment by DBendit** [comment]
Created https://github.com/dtandersen/docker_factorio_server/pull/185 to add support for the new files and config for handling bans and admins. As it stands, the `admins` setting in server-settings.json doesn't do anything anymore.

**Comment by zskullz** [comment]
Created [#186](https://github.com/dtandersen/docker_factorio_server/pull/186) to fix:

 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "filesystem error: create_directories "/opt/factorio/temp/currently-playing" failed: Permission denied [/opt/factorio/temp/currently-playing]"

experienced by myself and @nexusmaniac

**Comment by dtandersen** [comment]
Make a /temp folder next to saves and chmod it. Will check it out later.

**Comment by nexusmaniac** [comment]
I used 0.17.1 instead of latest and this:
https://github.com/dtandersen/docker_factorio_server/issues/184#issuecomment-467657758

Issue went away 😁

**Comment by tjsd** [comment]
On 0.17.1 I still get this:
`0.626 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "filesystem error: create_directories "/opt/factorio/temp/currently-playing" failed: Permission denied [/opt/factorio/temp/currently-playing]"`

I did make a temp directory inside my factorio folder and did chmod 855 on it. But that doesnt seem to fix the issue.

**Comment by nexusmaniac** [comment]
Hey @tjsd I know that `chmod 855` will open the permissions relatively widely but try `chown 845:845` on the folder instead 😄 

`/opt/factorio` lives inside the container, "your path" can be anything - mine is `/mnt/user/appdata/factorio/` 😄

**Comment by tjsd** [comment]
It is already like that:
![image](https://user-images.githubusercontent.com/7138125/53480275-294fe100-3a7b-11e9-895b-a0f8227328bc.png)

**Comment by nexusmaniac** [comment]
Try renaming your root folder to `factorio_backup` (or something) and restarting the container. It'll re-generate everything, see if the error still occurs.
_you can ignore that if you've already started fresh 😇_

I had problems with `latest` but not with `0.17-dev` 😎

**Comment by Terones** [comment]
hey @tjsd & @nexusmaniac, I had the same issue, it was solved by deleting the image (not the data) and pull it again.

**Comment by nexusmaniac** [comment]
`0.17.2` just dropped 👀

**Comment by DBendit** [comment]
> `0.17.2` just dropped

https://github.com/dtandersen/docker_factorio_server/pull/188

**Comment by dtandersen** [comment]
https://github.com/dtandersen/docker_factorio_server/commit/10d000408cdf80919fa1611d99973e544c92b9aa

**Comment by jasonwc** [comment]
Looks like they fixed the issue with the `map-gen-settings.example.json` in [0.17.2](https://forums.factorio.com/viewtopic.php?t=65311)

**Comment by DBendit** [comment]
> Looks like they fixed the issue with the `map-gen-settings.example.json` in [0.17.2](https://forums.factorio.com/viewtopic.php?t=65311)

https://github.com/dtandersen/docker_factorio_server/pull/189

**Comment by philippguertler** [comment]
0.17.2 image does not work for me.
```
factorio_1  | + set -e
factorio_1  | + id
factorio_1  | uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
factorio_1  | + FACTORIO_VOL=/factorio
factorio_1  | + mkdir -p /factorio
factorio_1  | + mkdir -p /factorio/saves
factorio_1  | + mkdir -p /factorio/config
factorio_1  | + mkdir -p /factorio/mods
factorio_1  | + mkdir -p /factorio/scenarios
factorio_1  | + mkdir -p /factorio/script-output
factorio_1  | + '[' '!' -f /factorio/config/rconpw ]
factorio_1  | + '[' '!' -f /factorio/config/server-settings.json ]
factorio_1  | + '[' '!' -f /factorio/config/map-gen-settings.json ]
factorio_1  | + '[' '!' -f /factorio/config/map-settings.json ]
factorio_1  | + find -L /factorio/saves -iname '*.tmp.zip' -mindepth 1 -print
factorio_1  | + grep -q .
factorio_1  | + find -L /factorio/saves -iname '*.zip' -mindepth 1 -print
factorio_1  | + grep -q .
factorio_1  | + id -u
factorio_1  | + '[' 0 '=' 0 ]
factorio_1  | + chown -R factorio:factorio /factorio
factorio_1  | + chown -R factorio:factorio /opt/factorio/temp
factorio_1  | chown: /opt/factorio/temp: No such file or directory
```

**Comment by philippguertler** [comment]
ok, you already fixed it. Thanks :)

**Comment by philippguertler** [comment]
`0.17.3` is out

**Comment by DBendit** [comment]
> `0.17.3` is out

https://github.com/dtandersen/docker_factorio_server/pull/193

**Comment by Fank** [comment]
@dtandersen as i wrote in my mail, the watchdog is working. right now 0.17.14 was published, pushed and tagged.

**Comment by SuperSandro2000** [comment]
I am going to close this as 0.17 is supported. We are aware of issues with 0.17.36 not being released and actively working on a solution to release new versions faster and fully automated.
