### ISSUE TITLE
Su-exec setgroups not permitted

### ISSUE THREAD

**Issue by AerikAwesome** [dtandersen/docker_factorio_server#187]
Attempting to run this image results in the following error in the output log:
"su-exec: setgroups: Operation not permitted"

Full output according to Portainer:
`
+ set -e
+ id
uid=845(factorio) gid=845(factorio) groups=845(factorio)
+ FACTORIO_VOL=/factorio
+ mkdir -p /factorio
+ mkdir -p /factorio/saves
+ mkdir -p /factorio/config
+ mkdir -p /factorio/mods
+ mkdir -p /factorio/scenarios
+ mkdir -p /factorio/script-output
+ '[' '!' -f /factorio/config/rconpw ]
+ '[' '!' -f /factorio/config/server-settings.json ]
+ '[' '!' -f /factorio/config/map-gen-settings.json ]
+ '[' '!' -f /factorio/config/map-settings.json ]
+ find -L /factorio/saves -iname '*.tmp.zip' -mindepth 1 -print
+ grep -q .
+ find -L /factorio/saves -iname '*.zip' -mindepth 1 -print
+ grep -q .
+ id -u
+ '[' 845 '=' 0 ]
+ cat /factorio/config/rconpw
+ exec su-exec factorio /opt/factorio/bin/x64/factorio --port 34197 --start-server-load-latest --server-settings /factorio/config/server-settings.json --server-banlist /factorio/config/server-banlist.json --rcon-port 27015 --server-whitelist /factorio/config/server-whitelist.json --use-server-whitelist --rcon-password aeshah6ai4Oop4l --server-id /factorio/config/server-id.json
su-exec: setgroups: Operation not permitted`

**Comment by dtandersen** [comment]
In this case the container is run as uid 845, so we don't need to su-exec. 

https://github.com/dtandersen/docker_factorio_server/releases/tag/0.17.1-2 removes the unnecessary su-exec. 

Make sure the factorio volume is owned by 845. I'm not familiar with Portainer.
