### ISSUE TITLE
17.4 still running as 17.3

### ISSUE THREAD

**Issue by Archivis** [dtandersen/docker_factorio_server#196]
Just did a pull of the latest and I'm not able to pull down a 17.4.

0.000 2019-03-01 21:47:21; Factorio 0.17.3 (build 43128, linux64, headless)

REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
docker.io/dtandersen/factorio     latest              012f8b2b92ad        25 hours ago        173 MB

Says 25 hours ago despite github showing updated.

I'm using this:

docker pull dtandersen/factorio:latest

I also tried using 0.17.4 instead of the latest flag.

**Comment by DBendit** [comment]
Looks like 17.4 just built about 15 minutes ago. Give it another shot now.

**Comment by Archivis** [comment]
Thanks.  17.4 tag works.  Latest is still pulling 17.3

**Comment by DBendit** [comment]
Looks like an issue on Dockerhub. @dtandersen needs to resolve it.

**Comment by jasonlotito** [comment]
It's been updated.  Can confirm latest and 0.17.4 work as expected.

**Comment by dtandersen** [comment]
Docker Hub is having some issues today.
