### ISSUE TITLE
Latest/0.17 on dockerhub still pointing to 0.17.9

### ISSUE THREAD

**Issue by msmollin** [dtandersen/docker_factorio_server#213]
Title says it all. Should be pointed at 0.17.11?

**Comment by DeliciousJaffa** [comment]
Latest is 0.17.9
0.17 is 0.17.10
![image](https://user-images.githubusercontent.com/2257490/54169877-83ce4180-446c-11e9-8cdb-937050691f1d.png)

**Comment by xatang** [comment]
Why is not updated the Latest tag? Something seems to have gone wrong. :/

**Comment by patschi** [comment]
It's also strange that "0.17" still points to 0.7.10, while 0.7.11 was already pushed.

**Comment by dtandersen** [comment]
If someone wants to automate 0.17/latest I can give docker hub perms.

**Comment by Fank** [comment]
I can could do that

**Comment by dtandersen** [comment]
You have it

**Comment by Fank** [comment]
But i don't see any options to change the build settings

**Comment by SuperSandro2000** [comment]
I would recommend to switch to travis and not stop using docker hub.
It is painfully slow and has little options.

Maybe my docker repo helps switching
https://github.com/SuperSandro2000/docker-images/blob/master/archisteamfarm/Makefile
https://github.com/SuperSandro2000/docker-images/blob/master/.travis.yml

If you want some more infos feel free to write me a mail or on discord.

**Comment by DeliciousJaffa** [comment]
While I was waiting for this repo to update, I setup my own fork with automatic build settings in docker hub, they're setup as follows (enter exactly the same as shown in table, do not replace anything):

Source Type | Source | Docker Tag |Dockerfile location | Build Context
------------- | -------- | ------------- | ------------------- | -------------
Branch | master | latest | Dockerfile | /0.17/
Tag | /^0.17.[0-9.]+$/ | 0.17 | Dockerfile | /0.17/
Tag | /^0.17.[0-9.]+$/ | {sourceref} | Dockerfile | /0.17/

**Comment by DeliciousJaffa** [comment]
@dtandersen Could you confirm if the above is in place or not, 0.17 and latest are still the (wrong) previous version.

**Comment by dtandersen** [comment]
I set it up that way now Jaffa. What is your Docker Hub name?

**Comment by DeliciousJaffa** [comment]
DockerHub username is `jaffa`

**Comment by DeliciousJaffa** [comment]
My DockerHub username is `Jaffa`

**Comment by dtandersen** [comment]
I added you as a collaborator there.

**Comment by patschi** [comment]
This seems working fine now, so I'd say this can be closed.
