### ISSUE TITLE
Environment variable for PUID/PGID

### ISSUE THREAD

**Issue by danstis** [dtandersen/docker_factorio_server#214]
Do you have any plans to allow configuration of the PUID/PGID via environment variables?

**Comment by AeonLucid** [comment]
This is something I'd like to see as well, it's useful for unraid. I'm unsure on how to implement it myself.

For those wondering what PUID/PGID is, it is something used by linuxserver.io containers.
More info:
- https://www.linuxserver.io/docs/puid-pgid/
- https://www.reddit.com/r/docker/comments/9iwe3t/where_can_i_find_out_how_puid_and_pgid_are_used/

**Comment by AeonLucid** [comment]
@danstis I have forked this repository and modified it to use a linuxserver.io image as base for PUID/PGID support, see https://github.com/AeonLucid/UnraidFactorio.

**Comment by danstis** [comment]
@AeonLucid - Certainly using the linuxServer base image is an option (thanks for the example repo).
I think I would prefer to use the existing dtanderson dockerfile. 
From what I can see I think this should be as simple as moving the PUID and PGID arguments to the environment variables in the existing dockerfile. I'll give it a test when I get a chance.

**Comment by AeonLucid** [comment]
That's fine, I plan on switching back to this repo once there is proper support.
-
I don't think that that will work since [build argument variables](https://docs.docker.com/engine/reference/builder/#arg) are used when the image is being build.
The only usage of the `PUID` and `PGID` build arguments is in the [Dockerfile](https://github.com/dtandersen/docker_factorio_server/blob/662372a1bad597aedfacd382893580b750be5747/0.17/Dockerfile#L34) which means it probably is not as easy as you said.

**Comment by danstis** [comment]
I would imagine that it should be a simple as adding the following to the ENV:
```
PUID=${PUID} \
PGID=${PGID}
```
This should create two new environment variables that default to the values of the ARGs PUID and PGID.
Am I missing something?

**Comment by AeonLucid** [comment]
Yes but those environment variables are not used by anything. PUID and PGID are not standard and there is not script using them.

**Comment by danstis** [comment]
They are used on Line 34 & 35: https://github.com/dtandersen/docker_factorio_server/blob/662372a1bad597aedfacd382893580b750be5747/0.17/Dockerfile#L34
https://github.com/dtandersen/docker_factorio_server/blob/662372a1bad597aedfacd382893580b750be5747/0.17/Dockerfile#L35

**Comment by danstis** [comment]
> They are used on Line 34 & 35:
> 
> [docker_factorio_server/0.17/Dockerfile](https://github.com/dtandersen/docker_factorio_server/blob/662372a1bad597aedfacd382893580b750be5747/0.17/Dockerfile#L34)
> 
> Line 34 in [662372a](/dtandersen/docker_factorio_server/commit/662372a1bad597aedfacd382893580b750be5747)
> 
>  addgroup -g $PGID -S $GROUP && \ 
> 
> [docker_factorio_server/0.17/Dockerfile](https://github.com/dtandersen/docker_factorio_server/blob/662372a1bad597aedfacd382893580b750be5747/0.17/Dockerfile#L35)
> 
> Line 35 in [662372a](/dtandersen/docker_factorio_server/commit/662372a1bad597aedfacd382893580b750be5747)
> 
>  adduser -u $PUID -G $GROUP -s /bin/sh -SDH $USER && \

Ahhh, yes they are only used in the build... agreed. 
Just thought it through!

**Comment by SuperSandro2000** [comment]
IIRC s6 does the PUID/GUID stuff
This should help you https://github.com/linuxserver/docker-baseimage-alpine/blob/master/Dockerfile

**Comment by AeonLucid** [comment]
@SuperSandro2000 this part is necessary too.
https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/cont-init.d/10-adduser
