### ISSUE TITLE
0.17.23 failing to download with curl

### ISSUE THREAD

**Issue by DBendit** [dtandersen/docker_factorio_server#225]
For whatever reason, 0.17.23 can't be downloaded with curl, which is making the Docker build fail.

```
curl -L https://www.factorio.com/get-download/0.17.23/headless/linux64
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

When I visit the same URL in the browser, factorio_headless_x64_0.17.23.tar.xz is downloaded as expected.

**Comment by Fank** [comment]
Thanks for the info ill check than when im at home

**Comment by bplein** [comment]
There is a problem with the Factorio web site. You can't download 3 of their 4 different packages from the page at https://www.factorio.com/download/experimental. It's a factorio.com problem, not a problem with this code.

**Comment by DBendit** [comment]
Right, but we'll want to make sure the SHA1 was generated off the appropriate file when it's resolved on their end.

**Comment by bplein** [comment]
That too! :)

**Comment by bplein** [comment]
I opened a bug report on factorio.com forums, and it seems that different people are seeing different 404 errors. Their CDN seems to be at fault. So even if we can individually download it, if the build servers cannot, then this will fail.

**Comment by ryanneufeld** [comment]
does anyone have built image in the docker repo we can use?

**Comment by bplein** [comment]
if you are able to download the Linux headless server (some can, some cannot), then use this dockerfile and build your own directly on the host you are using!

**Comment by ryanneufeld** [comment]
what's funny, is that i can download it on my docker host, but when I build
the image, docker cannot

--Ryan Neufeld BSc CIS
ryan@neufeldmail.com

**Comment by bplein** [comment]
I am going to try and build it right now. I cannot download it at home but I can in another location, if I can do so, I'll post it here. Check the SHA1 of the one you downloaded and compare it to the Dockerfile as well.

**Comment by ryanneufeld** [comment]
it downloads fine, so maybe something is up with the base container?

69eb89ecdfb8a1dc0b51415870200368950a677a


--Ryan Neufeld BSc CIS
ryan@neufeldmail.com

**Comment by bplein** [comment]
Docker does something weird with DNS, I'm seeing the same thing (host can curl the file, docker build fails). Still playing with it.

**Comment by ryanneufeld** [comment]
--dns 208.67.222.222 --dns 208.67.220.220
I'm using that for my DNS, which is the same as my entire network

--Ryan Neufeld BSc CIS
ryan@neufeldmail.com

**Comment by bplein** [comment]
OK, so one of the CDN hosts IPs has the file, one does not.

Use this syntax to force the DNS inside Docker to build from the one that has it:
`sudo docker build --add-host dcdn.factorio.com:45.56.70.196 -t bplein/tempfactorio:0.17.23 .`

**Comment by bplein** [comment]
I haven't tested it yet, and you really shouldn't trust random container images, but here's this build, rebuilt on my own system with the above command: bplein/tempfactorio:0.17.23

**Comment by ryanneufeld** [comment]
Your suggestion worked perfectly. Thanks
--Ryan Neufeld BSc CIS
ryan@neufeldmail.com

**Comment by bplein** [comment]
This is the first time I've run into this issue with building and DNS getting in the way. Docker apparently has it's own rules for how it gets DNS, I found this bug report: https://github.com/moby/moby/issues/25537

**Comment by Fank** [comment]
How ever i build it manual and pushed it to docker hub.

**Comment by bplein** [comment]
Everyone, I'm going to delete my image. Please use the official image going forward. I'll delete it later today.

**Comment by BShurilla** [comment]
Looks like this might have been closed a little too soon? Looks like the image on docker is still on 17.22 for latest, instead of now being 17.24

**Comment by bplein** [comment]
There is a 0.17.23 image available, it was hand-pushed so the docker page doesn't show it clearly.

The links are still flaky at the download site, so these automated builds will still continue to fail. Maybe @Fank can push another hand-built version.
