### ISSUE TITLE
0.17 docker update frequency?

### ISSUE THREAD

**Issue by Rawh** [dtandersen/docker_factorio_server#228]
Hi,

Docker is still at 0.17.23. Your github is already 0.17.24. I'd love to continue usage of your image, but it's a bit hard if I want to test out the new 0.17 branch, because latest is currently pointing to the .23 image from 4 days ago. 

What is the update frequency of your hub.docker.com releases? Can you perhaps adjust it to build more frequently?

Thanks in advance!

-- Rawh

**Comment by MagicHack** [comment]
The builds have failed because of this issue for the docker
https://forums.factorio.com/viewtopic.php?f=7&t=68716&p=419403

Seems like it has been resolved now, so restarting the builds should work

**Comment by Fank** [comment]
I can't retrigger the build, so i build and pushed it. 0.17.24 is now on docker hub, ignore the outdated readme, it should be fixed with the next builds.

**Comment by Rawh** [comment]
Thanks for the quick reply and fix!
