### ISSUE TITLE
Add option for map upload slots

### ISSUE THREAD

**Issue by jeffrey1681** [dtandersen/docker_factorio_server#230]
In 0.17.30 the changelog has the following item:
"Added ability to set a maximum number of map upload slots for multiplayer servers. Setting this is recommended to prevent the server from being flooded with map fragment requests from clients."

This should likely be added as an option to this image.

**Comment by danstis** [comment]
In your mapped volume under the `config` folder you should have a `server-settings.json` file. Check this file for the configuration item `max_upload_slots`.
I believe this is the configuration item that you are talking about.

**Comment by jeffrey1681** [comment]
Yeah, that's it. For some reason I thought it was an image setting and not just in the .json. Thanks.
