### ISSUE TITLE
Unraid 0.17.32 doesnt start

### ISSUE THREAD

**Issue by Rawh** [dtandersen/docker_factorio_server#231]
Hello,

When updating to the latest release on docker (0.17.32) my startup script no longer wants to run the server.

Startup line:
> docker run --rm -d -e PUID="99" -e PGID="100" -p 34197:34197/udp -p 27015:27015/tcp -v /mnt/user/appdata/factorio:/factorio --name factorio dtandersen/factorio:latest

When I remove the --rm part and run above command, followed by a `docker logs`, I get the following:

Docker Logs:
```+ set -e
+ id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
+ FACTORIO_VOL=/factorio
+ mkdir -p /factorio
+ mkdir -p /factorio/saves
+ mkdir -p /factorio/config
+ mkdir -p /factorio/mods
+ mkdir -p /factorio/scenarios
+ mkdir -p /factorio/script-output
+ '[' '!' -f /factorio/config/rconpw ]
+ '[' '!' -f /factorio/config/server-settings.json ]
+ '[' '!' -f /factorio/config/map-gen-settings.json ]
+ '[' '!' -f /factorio/config/map-settings.json ]
+ find -L /factorio/saves -iname '*.tmp.zip' -mindepth 1 -print
+ grep -q .
+ id -u
+ '[' 0 '=' 0 ]
+ usermod -u 99 factorio
+ groupmod -g 100 factorio
groupmod: GID '100' already exists 
```

It stops after the above groupmod
The PUID 99 and PGID100 are the default ones used within Unraids docker setup (and usually bind to the user inside of a container). Mostly "abc", but "factorio" in your case.

**Comment by Fank** [comment]
@danstis

**Comment by danstis** [comment]
I'm not at home for the next couple of days, so I can't check, but there is likely an issue with default groups within the container.
You should be no worse off if you leave these environment variables out, as this should default to the original behaviour.
I'll check what options are available when I get back home.

**Comment by Rawh** [comment]
Guess I could've figured that one out myself, 👍 

At least the container runs now and me and my friends can play 🗡

**Comment by Rawh** [comment]
Hmm seems the default image the dockerfile is created from "suddenly" includes a group called "users" which uses PGID 100 :(
```
/bin # cat /etc/group
root:x:0:root
bin:x:1:root,bin,daemon
daemon:x:2:root,bin,daemon
sys:x:3:root,bin,adm
adm:x:4:root,adm,daemon
tty:x:5:
disk:x:6:root,adm
lp:x:7:lp
mem:x:8:
kmem:x:9:
wheel:x:10:root
floppy:x:11:root
mail:x:12:mail
news:x:13:news
uucp:x:14:uucp
man:x:15:man
cron:x:16:cron
console:x:17:
audio:x:18:
cdrom:x:19:
dialout:x:20:root
ftp:x:21:
sshd:x:22:
input:x:23:
at:x:25:at
tape:x:26:root
video:x:27:root
netdev:x:28:
readproc:x:30:
squid:x:31:squid
xfs:x:33:xfs
kvm:x:34:kvm
games:x:35:
...
users:x:100:games
ntp:x:123:
nofiles:x:200:
...
...
factorio:x:1000:factorio
```

**Comment by SuperSandro2000** [comment]
Did you try PUID/GUID 1000?

**Comment by Rawh** [comment]
> 
> 
> Did you try PUID/GUID 1000?

Yes, as you can see above. That works because 1000 isn't taken.

**Comment by danstis** [comment]
Looks as though I should have used the -o switch on usermod and groupmod in order to allow non-unique IDs. I will raise a pull request with this addition.
I have just tested this with the `-e PUID="99" -e PGID="100"` and it starts fine with this modification.
