### ISSUE TITLE
Trying to build 0.17.32 locally, illegal option for /bin/sh

### ISSUE THREAD

**Issue by Rawh** [dtandersen/docker_factorio_server#233]
Hi,

I'm trying to build the image locally by cloning this repo and using 'docker build -t test .' inside the 017 directory. The image building goes ok but for some reason the container is never started, when I type "docker run -t -d -v <windowspath>:/factorio fact'. The container itself runs into and error which is best described by the image below.

I've narrowed down the error to the entrypoint script. Anyone got any idea what's going on? Could it be the "#!/bin/sh -x" part at the top?

![image](https://user-images.githubusercontent.com/10486655/56469080-19c69600-6435-11e9-9803-ee7449818743.png)

-- Rawh

**Comment by Rawh** [comment]
Hmm all .sh script have the same issue. When I copy it's content and execute it manually however, there are no errors / issues.

**Comment by SuperSandro2000** [comment]
On what system did you build your image?

I tested it with
````
docker build -t test .
````
and
````
docker run --rm -it -v :/factorio test
````
and got it running with no problems.

The shebang ``#!/bin/sh -x`` just tells linux to execute the script with that command. ``-x`` shows you the executed commands.

**Comment by Rawh** [comment]
Seems the bug is gone with building 0.17.36 locally, which works fine. As does starting the container! No clue what triggered it, glad it's gone though :)
