### ISSUE TITLE
Deploy to AWS with Spot Pricing (ECS, EFS) - Template Linked

### ISSUE THREAD

**Issue by m-chandler** [dtandersen/docker_factorio_server#235]
Hi, this probably isn't the best place to bring this up... but here goes!

I've put together a CloudFormation template to perform a complete deployment of a Factorio server to AWS using your docker images. Scenarios won't work at present, as this isn't something I've looked at yet.

Optionally it can use spot instances rather than on-demand, here in Australia they're generally super cheap and very reliable. State is persisted to EFS, so the server itself is ephemeral.

I'm currently using this template to run an 0.17 server for me and a few friends. I shut it down when not in use to save on running costs.

Anyway, take a look, if you're interested I can submit a PR updating the readme with links to my repo.

https://github.com/m-chandler/factorio-spot-pricing

**Comment by dtandersen** [comment]
I think this is worthy of a link from our readme to your github.

**Comment by m-chandler** [comment]
Closing, this has been merged.
