### ISSUE TITLE
Docker Hub "latest" tag did not auto-update

### ISSUE THREAD

**Issue by brandonhoughton** [dtandersen/docker_factorio_server#236]
Apologies if this is a manual process, it seems that builds are automated and I would assume docker tagging is automated as well.

**Comment by Fank** [comment]
Its a known issue

**Comment by MagicHack** [comment]
It's most probably due to the hack of dockerhub
https://news.ycombinator.com/item?id=19763413

**Comment by Manpoozle** [comment]
@brandonhoughton As a workaround you can pull this down and build it on your instance. The following got me up and running:
`git clone https://github.com/dtandersen/docker_factorio_server.git`
`cd docker_factorio_server/0.17`
`docker build -t factorio_local_build .`
`sudo docker run -d   -p 34197:34197/udp   -p 27015:27015/tcp   -v /opt/factorio:/factorio   --name factorio_local_build   --restart=always   factorio_local_build `

**Comment by SuperSandro2000** [comment]
@Manpoozle just a friendly notice: You should probably add your user to the docker group instead of using sudo.
Then I am like 50 % sure that the name tag here is unnecessary and I personally dislike restart=always due to the risk of boot looping and not be able to docker stop the container.

**Comment by Manpoozle** [comment]
@SuperSandro2000 Good advice. Also if you don't do the name tag you're assigned a random name, which should work, just preference.

**Comment by Fank** [comment]
The Problem here is now that docker hub in general wont work for now, ill setup a new build system as a workaround.

**Comment by SuperSandro2000** [comment]
@Manpoozle you are probably right. Expected it to work like docker-compose.

@Fank there were quite some issues with docker hub in the past. Maybe it is a good idea. Let me know if you encounter trouble and need some help with it. I have some but not to much experience with Travis and pushing docker images.

**Comment by bastianh** [comment]
I know friends are using quay.io for several images.. maybe thats a viable alternative?

**Comment by SuperSandro2000** [comment]
I have mixed feelings about quay.io. It could complicate the pull process and would break updating for existing users. Switching the build env shouldn't be a problem as the end user does not notice it in any way (eg switch to maybe travis to better debug stuff, faster builds, etc.) but changing the registry could be problematic.

**Comment by danstis** [comment]
I agree with @SuperSandro2000, changing the registry could have quite an impact on existing users. 
I think the best idea is to move to build process to something like Travis-CI where we would have complete control over the build process. 

I saw that @mgh87 suggested that he could assist by creating a CI/CD pipeline. @mgh87 do you have a preferred build service?

**Comment by SuperSandro2000** [comment]
My preference would be travis cause I used it before but to be honest circle or any other service would probably work as well.

**Comment by Fank** [comment]
quary.io and docker hub, are the same because both host docker images. The only problem we have is the build system on docker hub.

In preparation of #229 i created a new organisation with a test repository https://github.com/factoriotools/docker_factorio_server_test .

My idea was to use gitlab ci but due some overhead and the problem of maintaining different tools, i would prefer travis too.

@SuperSandro2000 you have full access to the repo above, can you test travis integration?
I haven't used travis for a long time, so my knowledge is a bit rusty.

**Comment by SuperSandro2000** [comment]
I am on it over here: https://github.com/factoriotools/docker_factorio_server_test/commits/ci%2Bother

We should probably move this discussion to a new issue.

**Comment by SuperSandro2000** [comment]
I just saw that we have GitHub Actions unlocked. I have never seen it and I pretty sure it is new and my other repos don't have it. It might be an idea looking into that.

**Comment by Fank** [comment]
See https://github.com/dtandersen/docker_factorio_server/issues/229#issuecomment-488607081 for upcomming changes about the build system.
