### ISSUE TITLE
0.17.34 did not automatically release

### ISSUE THREAD

**Issue by proegssilb** [dtandersen/docker_factorio_server#239]
As per the title. Docker Hub's latest version is still 0.17.33. I'm sure I don't have access to check the build automation, but I would if I did.

**Comment by SuperSandro2000** [comment]
I can think of two things right now. Either @dtandersen didn't reconnect GitHub after the recent breach or the daily build didn't kick off yet.

I would check it when I had access but I don't have.
This is kinda related to this https://github.com/dtandersen/docker_factorio_server/issues/229#issuecomment-488254168 and the group we are in moving to. Which means the repo is probably moving and maybe the docker image location. We are also in moving to travis here https://github.com/factoriotools/docker_factorio_server_test/pull/1 .

Kinda getting off topic and a lot is happening right now so some issues are expected.

@Fank did already some of the moving stuff and I don't really know the current plans but I am sure we will work all the moving stuff out in the next weeks.

Until then my best advice is building the image by hand until Docker Hub behaves again or someone fixes it.

**Comment by danstis** [comment]
@Fank do you have rights to push to docker hub? Thinking that we can push this image manually.

**Comment by Fank** [comment]
See https://github.com/dtandersen/docker_factorio_server/issues/229#issuecomment-488607081 .
Give me some hours and than it should be up2date.
