### ISSUE TITLE
No docker images are being build

### ISSUE THREAD

**Issue by Sven-Niehus** [dtandersen/docker_factorio_server#243]
Since docker hub got hacked last week https://www.zdnet.com/article/docker-hub-hack-exposed-data-of-190000-users/ no new Docker image has been build this is because every GitHub user needs to reconnect Docker with GitHub as a security measurement.

**Comment by Fank** [comment]
https://github.com/dtandersen/docker_factorio_server/issues/229#issuecomment-488607081
