### ISSUE TITLE
please push update 0.17.36 to dockerhub

### ISSUE THREAD

**Issue by maddinthe** [dtandersen/docker_factorio_server#244]
Please push the recent update to dockerhub or fix the update mechanism

**Comment by SuperSandro2000** [comment]
See: https://github.com/dtandersen/docker_factorio_server/issues/229#issuecomment-488607081
When we finish the move fully the images will be updated automatically. Until then you need some patience.

**Comment by Fank** [comment]
0.17.36 is pushed manually
