### ISSUE TITLE
0.17.36 docker release?

### ISSUE THREAD

**Issue by Rawh** [dtandersen/docker_factorio_server#246]
Hi,

.36 is out but the docker tag latest, for the docker image over at https://hub.docker.com/r/dtandersen/factorio/tags is stuck at version .33. When can we expect an update?

![image](https://user-images.githubusercontent.com/10486655/57184328-6345c500-6eba-11e9-8283-874d2a235c11.png)

**Comment by Rawh** [comment]
Ah, to answer my own question. Docker Hub is currently read only according to https://success.docker.com/article/docker-hub-maintenance.

I will wait :)

**Comment by Fank** [comment]
https://github.com/dtandersen/docker_factorio_server/issues/229#issuecomment-488607081
