### ISSUE TITLE
Fix download for container 0.17.36+

### ISSUE THREAD

**Issue by SHLelieveld** [dtandersen/docker_factorio_server#249]
Hi all maintainers of this docker container.

Since 0.17.33 the website does not correctly represent the current version mentioned in the Dockerfile.
When I try to download the new version (docker pull dtandersen/factorio:0.17.36 it says it cannot find that image). although the dockerfile does seem to point to 0.17.36

Error:
$ sudo docker pull dtandersen/factorio:0.17.36
Error response from daemon: manifest for dtandersen/factorio:0.17.36 not found

Please correct the problem so we all can update... :)

Love the work, container is very stable and proper, just stuck now on 0.17.33...

Regards,   Stefan L

**Comment by Fank** [comment]
https://github.com/dtandersen/docker_factorio_server/issues/229#issuecomment-488607081
