### ISSUE TITLE
0.15.11

### ISSUE THREAD

**Issue by vlczero** [dtandersen/docker_factorio_server#25]
Hi guys thanks for the image but I have a problem when I pull the latest docker image. It gives me 0.15.10 not 0.15.11. I tested the latest and 0.15-dev tags and they both give 0.15.10.

**Comment by dtandersen** [comment]
Is 0.15.11 stable enough to promote to 0.15?

**Comment by bkuhl** [comment]
Factorio lists all 0.15 as experimental

**Comment by dtandersen** [comment]
I mean the 0.15 tag on docker hub. I'm wary since 0.15.6!

**Comment by bkuhl** [comment]
Yeah, I can understand.  What I'm saying is that Factorio lists all 0.15.* as experimental.  So any one of them could be unstable.  Because of semantic versioning, I think there's a common assumption that `0.15` will always represent the latest `0.15.*` build, regardless of stability.

**Comment by vlczero** [comment]
Not seeing any game breaking bugs reported on reddit or the forums for 0.15.11. I used the 0.15.11 tag for now. I do think you should just let latest really be the latest and if people want a "stable" version they can use a specific version for 0.15.* or the stable tag.

Anyway thanks for the fast response.

**Comment by bkuhl** [comment]
@dtandersen Of course it's up to you how you want to treat the tags, but players who are concerned about breaking changes to patch versions can always lock themselves down to `0.5.*` so they know it won't break.  Keeping `0.15` up to date with the latest patch version allows people the option to always use the latest version.

**Comment by dtandersen** [comment]
I think I came to the same conclusion last week, but I forgot.
