### ISSUE TITLE
Environment variable for port

### ISSUE THREAD

**Issue by emil-nasso** [dtandersen/docker_factorio_server#3]
First of all, love this image. Good stuff. :) 👍 

I would really like to be able to run multiple servers on the same ip.

The thing that is holding me back (i think) is this:
https://github.com/dtandersen/docker_factorio_server/blob/master/0.14/docker-entrypoint.sh#L31

It would be nice to change that into an environment variable and provide a default value for it to not break backwards compatibility. 

That would make it possible to specify port when you start up the container.

Do you see any reason why this wouldn't work? Would you be willing to look at/merge it if i tested it and created a pull request?

**Comment by AgentME** [comment]
Most images including the [official redis image](https://hub.docker.com/_/redis/) for example are coded to use a specific port. When you run the container, you specify the port mapping you want to use, allowing you to choose any port number on your host that you want.

This is the command from the readme:

```
docker run -d -p 34197:34197/udp -p 27015:27015/tcp \
  -v /tmp/factorio:/factorio \
  --name factorio \
  --restart=always  \
  dtandersen/factorio
```

If you wanted to host factorio on port 34198 instead of 34197, then you should change the `-p 34197:34197/udp` part to `-p 34198:34197/udp`.

**Comment by emil-nasso** [comment]
Yes, definitely. The problem is that the server is still running on the default port, as far as the factorio server software knows.

This is might all be based on false assumptions on my part. I wanted to be able to connect to my server through the server browser and run multiple servers on the same IP. To do that I need to change the port that the server actually run. If I just run it on the default port and change the port mapping in docker, the browser won't be aware of what port I'm actually listening to because the server can't report what it doesn't know.

This all assumes that when you connect through the server browser, you connect to the port the server is actually running on, not just the default port, all of the time.

I should test that first... :)

**Comment by dtandersen** [comment]
A couple of questions:

1. Does the server on port 34197 work?
2. Did you add `--userland-proxy=false` to `DOCKER_OPTS`.

Also, can you give these lines from the server and client logs?

```
Hosting game at 0.0.0.0:34197 # server log
Own address is 45.32.95.58:1024 # server log
Joining game 45.32.95.58:1024 # client log
```

From what I've seen, the server doesn't use --port to report its port to the server browser. The server browser detects the source port from the packet sent by the server.

However, it may be that the --port option could affect the source port. I don't know if the external world would see the port inside of Docker container or the port translated by Docker.

**Comment by emil-nasso** [comment]
I did some more testing here.

Just changing the port forwardning in docker did not work. Just setting a `-p 34198:34197` when starting the container doesn't make it possible to connect to that server through the serverbrowser.

Actually changing the --port does however work. That is the port that gets reported to the server browser. I'm currently running two servers on one ip, on different ports using this docker-compose file:

```yaml
version: "2"
services:
  one:
    build: docker_factorio_server/0.14
    restart: always
    environment:
     - "PORT=34197"
    ports:
     - "34197:34197/udp"
    volumes:
     - "./data1:/factorio"
  two:
    build: docker_factorio_server/0.14
    restart: always
    environment:
     - "PORT=34198"
    ports:
     - "34198:34198/udp"
    volumes:
     - "./data2:/factorio"
```

I cloned this repository and changed the file `0.14/docker-entrypoint.sh`. All i changed was `  --port 34197\` to `  --port $PORT \`

It would be nice to have this as a feature. What would be needed:

* Make the port change made above to read the port from `$PORT`.
* Set `$PORT` to its default value `34197` if it is not already set.
* Add information about this to the readme.

Do you want me to make these changes and create a pull-request?

**Comment by dtandersen** [comment]
Sure, send it over. A line `ENV PORT=34197` in the Dockerfile can set the default value.

**Comment by dtandersen** [comment]
Added this for 0.15. If it works I'll back port it.

**Comment by emil-nasso** [comment]
Ok. Great. Thanks! Sorry about the late response. :)

**Comment by dtandersen** [comment]
Still needed?

**Comment by emil-nasso** [comment]
The change in 0.15 is great. It's all that's needed. :) Thanks again
