### ISSUE TITLE
0.15 support

### ISSUE THREAD

**Issue by j2ghz** [dtandersen/docker_factorio_server#4]
0.15 should be available tomorrow, will you be adding support for it?

Source: https://www.factorio.com/blog/post/fff-187

**Comment by dtandersen** [comment]
Yep!

**Comment by j2ghz** [comment]
They lied, it's live now https://www.factorio.com/download-headless/experimental

**Comment by dtandersen** [comment]
It's building now :)

**Comment by MonkeyDrone** [comment]
Any of you even got the headless server to launch? 
Getting same issue like this guy https://gist.github.com/pvrs12/3a1a0ce0b05d9254fb0be82a19e8ef35
Might want to try get the server running before pushing forward with the build.

**Comment by dtandersen** [comment]
What were you doing? Maybe it will help somebody.

**Comment by Fank** [comment]
@dtandersen +1 from me for up2date tags :D
