### ISSUE TITLE
Suppress Logger for Info Items

### ISSUE THREAD

**Issue by jonfairbanks** [dtandersen/docker_factorio_server#55]
Is it possible to set the log level? A good majority of my log entries are duplicates of these two:

`
15723.267 Info HttpSharedState.cpp:109: Downloading https://multiplayer.factorio.com/create-game
15723.267 Info HttpSharedState.cpp:111: Status code: 401
`

**Comment by dtandersen** [comment]
I've not seen any options to do that. You might ask on the forum.

**Comment by jonfairbanks** [comment]
Thanks! Will open a PR if I learn anymore.
