### ISSUE TITLE
Broken saves prevent auto restarts

### ISSUE THREAD

**Issue by yukihyou** [dtandersen/docker_factorio_server#68]
This is more a Factorio "--start-server-load-latest" issue, but can be worked around here.

When restarting the container on my Jelastic host, Factorio realises it's going down and tries to save, but isn't given enough time, so a `*.tmp.zip` file is created, which is invalid. This file is obviously the latest modified one, and which the server tries to load.

Would it be possible to add a quick check into the docker-entrypoint file that basically does:

- touch most recent save file that doesn't contain `*.tmp.*`

This won't stop the folder filling up with broken saves, but it will at least allow automated (timed) restarts to work correctly.

**Comment by yukihyou** [comment]
I presume it should be as simple as this?
```
touch $SAVES/`ls $SAVES -rt |grep -v '.tmp.' |tail -n 1`
```

**Comment by dtandersen** [comment]
I'll take PR for it.
