### ISSUE TITLE
Permission denied /docker-entrypoint.sh

### ISSUE THREAD

**Issue by VonOx** [dtandersen/docker_factorio_server#87]
After update to the latest image

I have this error in the logs: ( with `docker logs factorio` )

`[FATAL tni (7)] exec /docker-entrypoint.sh failed: Permission denied`

I think #85 is not fixed
I'm wrong ?

**Comment by VonOx** [comment]
After rebuild its ok, so image need to be rebuild

**Comment by dtandersen** [comment]
re-tagged 0.15.40 and re-pushed the image to docker hub
