### ISSUE TITLE
Server not listed in LAN list

### ISSUE THREAD

**Issue by trevjonez** [dtandersen/docker_factorio_server#88]
Same config file outside of a docker container shows up in the lan browser. Important bits are:

```
  "visibility":
  {
    "public": false,
    "lan": true
  }
```

Seems like there may be an additional port that needs to be opened for broadcast?

**Comment by dtandersen** [comment]
You might try running with host networking or disabling userland proxy. It probably has something to do with broadcasting from within Docker.

**Comment by trevjonez** [comment]
Host networking indeed did the trick. Thank you.

**Comment by Blu3wolf** [comment]
> It probably has something to do with broadcasting from within Docker. The container (172.x.x.x) isn't in the LAN's IP (e.g. 192.168.x.x) range, so there would have to be a bridge or something.

This is interesting, as Docker sets up a bridge by default. Its probably still to do with configuring docker appropriately, but lack of a bridge shouldn't be the reason.

**Comment by Lizardbutt** [comment]
This is still an issue.
