### ISSUE TITLE
Advisory: 0.16 no longer runs as root

### ISSUE THREAD

**Issue by dtandersen** [dtandersen/docker_factorio_server#91]
You will need to change files to be owned by uid=845 gid=845 or run docker with --user user:group.

**Comment by aleksandrpak** [comment]
Can you give some more information on which files are you talking about?

**Comment by dtandersen** [comment]
The files in the volume you mount, notably folder the save file is in should be writable by that uid.

**Comment by aleksandrpak** [comment]
Does "Error in `/opt/factorio/bin/x64/factorio': free(): invalid pointer: 0x00000000018b3b60" mean that I've configured the files ownership badly?

**Comment by dtandersen** [comment]
Confirm you are using 0.16.1 instead of 0.16.0.

**Comment by aleksandrpak** [comment]
With update to 0.16.1 it works now. Thanks!
